version: '3.7'

services:
  api:
    build: api
    volumes:
      - ./api:/backend
    environment:
      - FLASK_APP=app.py
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - internal

  client:
    build:
      context: ./mocha
    volumes:
      - ./mocha:/frontend
      - node-modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - internal
    links:
      - api:api

volumes:
  node-modules:

networks:
  internal:

